[package]
name = "virtual_projectiles"
version = "0.1.0"
authors = ["ueco <ueco@libertymail.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tuple = { path = "../../tuple" }
